dbt_dskola_profile:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: new_password
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
