version: 2
sources:
  - name: staging
    database: postgres
    schema: public
    tables:
      - name: categories
      - name: customers
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: suppliers
